# Generated by Django 4.2.11 on 2024-05-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('tax', models.FileField(upload_to='tax_documents/')),
                ('proof', models.FileField(upload_to='proof_of_identifications/')),
                ('agreement', models.FileField(upload_to='agreements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='myeducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('fieldOfStudy', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
    ]
