# Generated by Django 4.2.11 on 2024-04-22 14:20

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('What_type_of_job_opportunities_are_you_most_interested_in', models.CharField(choices=[('Non-Entry-Level Positions', 'Non-Entry-Level Positions'), ('Entry-Level Positions', 'Entry-Level Positions')], max_length=255)),
                ('Are_you_interested_in_permanent_or_contract_job_opportunities', models.CharField(choices=[('Permanent Positions', 'Permanent Positions'), ('Contract Positions', 'Contract Positions')], max_length=255)),
                ('How_would_you_prefer_to_join_our_team', models.CharField(choices=[('Join with a new contract found by XenFlexer', 'Join with a new contract found by XenFlexer'), ('Join XenFlexer with a new contract I secure independently', 'Join XenFlexer with a new contract I secure independently'), ('Join XenFlexer with my current ongoing project', 'Join XenFlexer with my current ongoing project')], help_text='Applicable only if you selected "Contract Positions" above.', max_length=255)),
            ],
        ),
    ]
