# Generated by Django 4.2.11 on 2024-05-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentsupload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('certificate', models.FileField(upload_to='certificates/')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('tax', models.FileField(upload_to='tax_documents/')),
                ('proof', models.FileField(upload_to='proof_of_identifications/')),
                ('agreement', models.FileField(upload_to='agreements/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('docs', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=100, null=True)),
                ('graduation', models.CharField(blank=True, max_length=100, null=True)),
                ('fieldOfStudy', models.CharField(blank=True, max_length=100, null=True)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('my_edu', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MyExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('currentCompany', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('my_exp', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UploadResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(blank=True, null=True)),
                ('upload', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='VoluntaryDisclosures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectYESifyouareokayreceivingupdatesonnewjobsbeingposted', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255, null=True)),
                ('selectYESifyouareokayreceivingEmailNotificationforNewsletter', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255, null=True)),
                ('disclosure', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='agreement',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='currentCompany',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='disclosure',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='docs',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='fieldOfStudy',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='graduation',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='my_edu',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='my_exp',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='my_info',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='proof',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='school',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='selectYESifyouareokayreceivingEmailNotificationforNewsletter',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='selectYESifyouareokayreceivingupdatesonnewjobsbeingposted',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='startDate',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='upload',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='uploaded_at',
        ),
    ]
