# Generated by Django 4.2.11 on 2024-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_documentsupload_myeducation_myexperience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='my_info',
            field=models.BooleanField(default=False),
        ),
    ]
