# Generated by Django 4.2.11 on 2024-05-03 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_userdetails_my_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('startDdate', models.DateField()),
                ('endDate', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('applicableTo', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
