# Generated by Django 4.2.11 on 2024-04-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_salescontact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InterestSignup',
            new_name='JobOpportunity',
        ),
    ]
