# Generated by Django 4.2.11 on 2024-04-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_interestsignup_jobopportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='voluntary_disclosures',
            name='text',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voluntary_disclosures',
            name='Please_select_YES_if_you_are_okay_with_receivingEmail_Notification_for_Newsletter',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='voluntary_disclosures',
            name='Please_select_YES_if_you_are_okay_with_receiving_updates_on_new_jobs_being_posted',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetentry',
            name='approval_status',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Pending', 'Pending'), ('Rejected', 'Rejected')], max_length=20),
        ),
    ]
