# Generated by Django 4.2.11 on 2024-05-03 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_timesheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='startDdate',
            new_name='startDate',
        ),
        migrations.RenameField(
            model_name='timesheet',
            old_name='applicableTo',
            new_name='users',
        ),
    ]
