# Generated by Django 4.2.11 on 2024-04-23 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_timesheetentry_project_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voluntary_disclosures',
            old_name='Please_select_YES_if_you_are_okay_with_receivingEmail_Notification_for_Newsletter',
            new_name='select_YES_if_you_are_okay_with_receivingEmail_Notification_for_Newsletter',
        ),
        migrations.RenameField(
            model_name='voluntary_disclosures',
            old_name='Please_select_YES_if_you_are_okay_with_receiving_updates_on_new_jobs_being_posted',
            new_name='select_YES_if_you_are_okay_with_receiving_updates_on_new_jobs_being_posted',
        ),
    ]
