# Generated by Django 4.2.11 on 2024-04-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_select_yes_if_you_are_okay_with_receivingemail_notification_for_newsletter_voluntary_disclosu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='Are_you_interested_in_permanent_or_contract_job_opportunities',
            new_name='contract_type',
        ),
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='What_type_of_job_opportunities_are_you_most_interested_in',
            new_name='job_type',
        ),
        migrations.RenameField(
            model_name='jobopportunity',
            old_name='How_would_you_prefer_to_join_our_team',
            new_name='joining_preference',
        ),
    ]
