# Generated by Django 4.2.11 on 2024-04-24 10:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_are_you_interested_in_permanent_or_contract_job_opportunities_jobopportunity_contract_type_an'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConatctUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=70, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Reason_for_reaching_out', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
