# Generated by Django 4.2.11 on 2024-04-30 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0009_conatctus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='user',
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='user',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
