# Generated by Django 4.2.11 on 2024-04-30 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_remove_timesheetentry_user_timesheetentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetentry',
            name='user',
            field=models.ManyToManyField(related_name='timesheets', to=settings.AUTH_USER_MODEL),
        ),
    ]
