# Generated by Django 4.2.11 on 2024-04-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_timesheetentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheetentry',
            old_name='user',
            new_name='users',
        ),
    ]
