# Generated by Django 4.2.11 on 2024-04-30 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_timesheetentry_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopportunity',
            name='contract_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='job_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobopportunity',
            name='joining_preference',
            field=models.CharField(help_text='Applicable only if you selected "Contract Positions" above.', max_length=255),
        ),
    ]
